catch Exeptions (Token is invalid/Problem whith Internet)
polina-nn/echo-bot pull request #15
Opened 2022-12-01 11:55 UTC by polina-nn

2022-12-02 04:09 UTC, pavelzarubin requested changes

2022-12-02 04:09 UTC, pavelzarubin commented on src/FrontEnd/Telegram.hs
> +  maybeTgUpdate <-
при отправке сообщения исключения не обрабатываются

2022-12-04 09:43 UTC, polina-nn commented on src/FrontEnd/Telegram.hs
> +  maybeTgUpdate <-
![Снимок экрана 2022-12-04 в 11 08 04](https://user-images.githubusercontent.com/55196536/205480676-f397b761-83f0-49fb-9baa-7826154ed5b6.png)
Вопрос1.Я видимо, что-то не понимаю про обработку исключений. В моем понимании обработка исключений  (в 47 строчке) выбрасываемых из функций getTgUpdates или getMeTg заключается в отправке понятного сообщения в Log и на терминал и остановке бота.
Вопрос2:
  У меня получается есть три ошибки которые не зависят от действий пользователя телеграмм бота:
  - эксепшен при отключении интернета (тестировался)
  - эксепшен при неверном токене  (тестировался)
  - ошибка обозначенная в типе Content, когда в объекте Update от телеграмма приходит не Message и не     CallBackQery. Это может быть если телеграмм сменит  свой API  (не тестировался)
Наверное, третий вид ошибок тоже лучше определить в том же блоке где определены эксепшены. Так будет проще найти, где править код и правильнее для составления документации к боту. Пока не перенесла.

Вопрос3:
Когда я получаю тип HttpException из ответа от телеграмма: то тип имеет два констуктора:
VanillaHttpException и JsonHttpException. В версии отправленной ранее, в JsonHttpException я (не подумав) для полноты написала отправку ServiceAPIError .... Но до меня дошло, что эта ошибка возникает, когда например (возможно и в других случаях) изменились названия полей в АРI телеграмма. Я ее воспроизвела.  Изменения внесла.
![Снимок экрана 2022-12-04 в 12 29 43](https://user-images.githubusercontent.com/55196536/205483888-1934ced4-a12c-4fb8-a509-701bd2e6e2b0.png)

Вопрос4: 
Пожалуй самый частый эксепшен 
*** Exception: logs: openFile: resource busy (file is locked)
С ним мы ничего делать не будем??? Просто в инструкции напишем, что нужно вручную закрыть файл и запустить бот снова.

2022-12-04 12:50 UTC, polina-nn commented on src/FrontEnd/Telegram.hs
> +  maybeTgUpdate <-
ну и соответственно, если из типов убрать поля, который бот не парсит, то вероятность JsonHttpException уменьшится. (Скорее всего программа просто не заработает если в API телеграмма поменяют названия полей, которые явно используются в функциях бота). Я просто пытаюсь найти ЕЩЁ веские причины не парсить поля, которые не используются. Было же такое замечание. Это сделаю, как все ишью закрою. Ну и readme  поправлю.
А так (из опыта), когда ещё этот JsonHttpException String (A wrapper with Aeson-produced String describing why decoding failed) возникает?

2022-12-05 06:36 UTC, pavelzarubin commented on src/FrontEnd/Telegram.hs
> +  maybeTgUpdate <-
Вопрос1. Ну да все верно. Это я видимо коммент ткнул в эту строчку. Но вообще можно обработать по-другому. Ты ловишь исключения вот так
```haskell
EX.catch (TgAPI.getMeTg token) (handleException h)
```
А можно ловить отдельным хендлером, ко всей функции. То есть ты сможешь отлавливать и те исключения, которые бросают функции из стандартных библиотек,  так же ты сможешь свои исключения прописать и их отлавливать, тем самым у тебя будет меньше ветвлений. Такой подход спасет вообще от всех исключительных ситуаций. Делать необязателно, то что сделано в принципе достаточно.
[пункт 8](https://coda.io/@metalamp/education/5-16) про исключения.

Вопрос 2.3 Да все так, про изменении апи не стоит беспокоится, не думаю что телеграмм внесет сильные изменения, или прекратит поддержку старых версий. У вк например для этого есть отдельное поле, в котором указываешь версию апи, которую используешь.
Но у тебя не хватает проверки исключения, когда бот отправляет сообщение. Да это кажется маловероятным, да и я чтобы это провернуть немного код модифицировал, но такая ошибка вполне может возникнуть.

Вопрос 4. А  к какой файл у нас может быть занят? Из конфига мы только считываем данные и его не трогаем. 
Логи у тебя создаются при запуске. Ну в принципе да, просто сообщи о перезапуске, главное сообщить какой файл занят. Если копать глубже, можно еще кидать сообщение о доступе к файлу. Вдруг там полный запрет.

2022-12-05 06:39 UTC, pavelzarubin commented on src/FrontEnd/Telegram.hs
> +  EX.throwIO e
замени на exitfailure, а то выглядит, что ты дальше пробрасываешь ошибку и программа завершается с помощью error, и печатает сообщение дважды.

2022-12-05 06:39 UTC, pavelzarubin approved these changes

2022-12-05 06:41 UTC, pavelzarubin requested changes
Доделай обработку при отправке сообщений от бота.

2022-12-05 06:56 UTC, pavelzarubin commented on src/FrontEnd/Telegram.hs
> +  maybeTgUpdate <-
> ну и соответственно, если из типов убрать поля, который бот не парсит, то вероятность JsonHttpException уменьшится. (Скорее всего программа просто не заработает если в API телеграмма поменяют названия полей, которые явно используются в функциях бота). Я просто пытаюсь найти ЕЩЁ веские причины не парсить поля, которые не используются. Было же такое замечание. Это сделаю, как все ишью закрою. Ну и readme поправлю. А так (из опыта), когда ещё этот JsonHttpException String (A wrapper with Aeson-produced String describing why decoding failed) возникает?

ну тогда и возникает, когда json не парсится)
Ну еще смотри, допустим ты из 20 полей используешь 3, и перегоняешь данные туда сюда для обработки. Это неэффективно. К тому же лишние поля тоже могут не распарсится. Другое дело если бы мы писали бибилиотеку для работу с апи, тогда да, мы бы парсили все поля. Но здесь задача в другом. (а еще ее можно было сделать еще проще для телеграмма, но я не скажу как))

2022-12-07 15:27 UTC, polina-nn commented
Добавила ловлю ошибок при вызове функции TgAPI.sendTgResponse ну и отправку ошибок в TgAPI.sendTgMessage. 
и возврат кода ошибки  exitFailure  со словами "*** Exception:......"

2022-12-08 10:43 UTC, merged